image: python:3.12-slim

pages:
  stage: deploy
  # before_script:
  #   - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  #   - eval $(ssh-agent -s)
  #   - chmod 400 "$SSH_PRIVATE_KEY"
  #   - ssh-add "$SSH_PRIVATE_KEY"
  #   - mkdir -p ~/.ssh
  #   - chmod 700 ~/.ssh
  script:
    - pip install -r requirements-docs.txt
    - mkdocs build --site-dir public
    # - scp -r -o "UserKnownHostsFile=$KNOWN_HOSTS" -i"$SSH_PRIVATE_KEY" public/* pycatap@projects.astec.ac.uk:/var/www/html/janus
  artifacts:
    paths:
      - public
  only:
    - main
    - develop
