include: 
  - ./compose/server.yaml

services:
  restframe:
    build:
      args:
        FACILITY: ${FACILITY:-JFEL}
        LAURA_LATTICE_REPO: ${LAURA_LATTICE_REPO}
    extends:
      file: ./compose/server.yaml
      service: restframe
    environment:
      - FACILITY=${FACILITY:-JFEL}
      - RESTFRAME_PORT=${RESTFRAME_PORT:-8000}
  lattice_api:
    extends:
      file: ./compose/server.yaml
      service: lattice_api
    environment:
      - FACILITY=${FACILITY:-JFEL}