include:
  - compose/core.yml
  - compose/clara.yml

services:
  restframe:
    extends:
      file: compose/overrides.yml
      service: restframe
    environment:
      - FACILITY=CLARA
    volumes:
      - ./apps/api/restframe/CLARA:/home/web/webapp/Output/CLARA

  sandbox:
    extends:
      file: compose/overrides.yml
      service: sandbox
    user: "janus-developer"
    environment:
      - EPICS_CA_SERVER_PORT=6090
      - EPICS_PVA_NAME_SERVERS=physics_iocs:${PHYSICS_PORT:-6091}
  
  lattice_api:
    extends:
      file: compose/overrides.yml
      service: lattice_api
    env_file:
      - ./apps/api/lattice/.env.dev
    environment:
      - FACILITY=CLARA

  frontend:
    extends:
      file: compose/overrides.yml
      service: frontend
