include:
  - compose/server.yaml
  - compose/client.yaml
  - compose/isis.yml

services:
  restframe:
    build:
      args:
        FACILITY: ISIS
        LAURA_LATTICE_REPO: git@gitlab.stfc.ac.uk:xkc85723/laura-lattices.git
    extends:
      file: compose/server.yaml
      service: restframe
    environment:
      - FACILITY=ISIS
      - LAURA_LATTICE_REPO=git@gitlab.stfc.ac.uk:xkc85723/laura-lattices.git
    volumes:
      - ./apps/api/restframe/ISIS:/home/web/webapp/Output/ISIS
  sandbox:
    extends:
      file: compose/client.yaml
      service: sandbox
    user: "janus-developer"
    environment:
      - EPICS_PVA_BROADCAST_PORT=${PORT:-6090} # to allow udp coms inside the stack
      - EPICS_PVA_AUTO_ADDR_LIST=YES
      - EPICS_PVA_NAME_SERVERS=physics_iocs:${PHYSICS_PORT:-6091} ioc:${PORT:-6090}
  lattice_api:
    extends:
      file: compose/server.yaml
      service: lattice_api
    environment:
      - FACILITY=ISIS
  hsds_backend:
    build:
      args:
        FACILITY: ISIS
    extends:
      file: compose/server.yaml
      service: hsds_backend
    volumes:
      - ./apps/api/restframe/ISIS:/data/filestore:ro
  pvws:
    extends:
      file: compose/client.yaml
      service: pvws
    depends_on:
      - ioc
    environment:
      - EPICS_PVA_NAME_SERVERS=physics_iocs:${PHYSICS_PORT:-6091} ioc:${PORT:-6090}
      - EPICS_CA_ADDR_LIST=ioc
      - EPICS_CA_SERVER_PORT=${PORT:-6090}
  # managing requests from changes in ISIS IOCs to the lattice API
  epics_to_lattice:
    build:
      context: ./services/isis/
      ssh:
        - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - physics_iocs
      - ioc
    environment:
      - EPICS_PVA_AUTO_ADDR_LIST=YES
      - EPICS_PVA_NAME_SERVERS=physics_iocs:${PHYSICS_PORT:-6091} ioc:${PORT:-6090}
      - EPICS_PVA_BROADCAST_PORT=${PORT:-6090}  # this is required to allow pvget to work in sandbox. It also doesn't have to be different to
      - PYTHONUNBUFFERED=1
      - VIRTUAL_MODE=True
      - FACILITY=ISIS
      - CLIENT_ID=${CLIENT_ID:-defaultclient}
      - LATTICE_API_HOST=${LATTICE_API_HOST:-host.docker.internal}
      - LATTICE_API_PORT=${LATTICE_API_PORT:-1337}
      - BROKER_HOST=${BOOTSTRAP_SERVERS:-host.docker.internal}
      - KAFKA_PORT=${KAFKA_PORT:-9092}
      - RESTFRAME_HOST=${RESTFRAME_HOST:-host.docker.internal}
      - RESTFRAME_PORT=${RESTFRAME_PORT:-8000}

      #- LATTICE_PARAMS={"dipoles":["CLA-VBC-MAG-DIP-01"],"generator":{"charge":"CLA-S01-DIA-WCM-01"}}

    volumes:
      - ./janus_common:/usr/src/app/janus_common