include:
  - compose/client.yaml
  - compose/clara.yml
services:
  pvws:
    extends:
      file: compose/client.yaml
      service: pvws
    depends_on:
      - ioc
    environment:
      - EPICS_CA_ADDR_LIST=ioc
      - EPICS_CA_SERVER_PORT=${PORT:-6090}
  sandbox:
    extends:
      file: compose/client.yaml
      service: sandbox
    user: "janus-developer"
    environment:
      - EPICS_CA_ADDR_LIST=ioc # 192.168.83.246 (original) # 192.168.83.255 (from ioc service)
      - EPICS_CA_MAX_ARRAY_BYTES=1000000000
      - EPICS_CA_SERVER_PORT=${PORT:-6090} # 6060 (original) # 6090 (from ioc service)
      - EPICS_PVA_AUTO_ADDR_LIST=YES
      - EPICS_PVA_NAME_SERVERS=physics_iocs:${PHYSICS_PORT:-6091}
      - EPICS_PVA_BROADCAST_PORT=${PVA_PORT:-6092}  # this is required to allow pvget to work in sandbox. It also doesn't have to be different to
  # managing requests from changes in CLARA IOCs to the lattice API
  epics_to_lattice:
    build: 
      context: ./services/clara/
      ssh:
        - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - physics_iocs
      - ioc
    environment:
      - EPICS_CA_ADDR_LIST=ioc # 192.168.83.246 (original) # 192.168.83.255 (from ioc service)
      - EPICS_CA_MAX_ARRAY_BYTES=1000000000
      - EPICS_CA_SERVER_PORT=${PORT:-6090} # 6060 (original) # 6090 (from ioc service)
      - EPICS_PVA_AUTO_ADDR_LIST=YES
      - EPICS_PVA_NAME_SERVERS=physics_iocs:${PHYSICS_PORT:-6091}
      - EPICS_PVA_BROADCAST_PORT=${PVA_PORT:-6092}  # this is required to allow pvget to work in sandbox. It also doesn't have to be different to
      - PYTHONUNBUFFERED=1
      - VIRTUAL_MODE=True
      - FACILITY=CLARA
      - CLIENT_ID=${CLIENT_ID:-defaultclient}
      - LATTICE_API_HOST=${LATTICE_API_HOST:-host.docker.internal}
      - LATTICE_API_PORT=${LATTICE_API_PORT:-1337}
      - BROKER_HOST=${BOOTSTRAP_SERVERS:-host.docker.internal}
      - KAFKA_PORT=${KAFKA_PORT:-9092}
      - RESTFRAME_HOST=${RESTFRAME_HOST:-host.docker.internal}
      - RESTFRAME_PORT=${RESTFRAME_PORT:-8000}

      #- LATTICE_PARAMS={"dipoles":["CLA-VBC-MAG-DIP-01"],"generator":{"charge":"CLA-S01-DIA-WCM-01"}}

    volumes:
      - ./janus_common:/usr/src/app/janus_common