include: 
  - ./compose/server.yaml

services:
  restframe:
    extends:
      file: ./compose/server.yaml
      service: restframe
    environment:
      - FACILITY=${FACILITY:-CLARA}
      - RESTFRAME_PORT=${RESTFRAME_PORT:-8000}
  lattice_api:
    extends:
      file: ./compose/server.yaml
      service: lattice_api
    environment:
      - FACILITY=${FACILITY:-CLARA}